### ISSUE TITLE
failure to create new room via the start chat UI

### ISSUE THREAD

**Issue by dduran1967** [wiresafe/wiresafe-deploy#2]
When authenticated via google / password, I tried to start a new conversation  via invitation to start a new chat with someone and get the error  "FAILURE TO CREATE ROOM".  I get the same error when inviting an existing user in firebase and a new user without a firebase account.

**Comment by maxidorius** [comment]
[Known issue](https://github.com/vector-im/riot-web/issues/5028)

**Comment by dduran1967** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [failure to create new room via the start chat UI #2](https://trello.com/c/AMSwHOPl/37-failure-to-create-new-room-via-the-start-chat-ui-2)

**Comment by dduran1967** [comment]
Fixed in wiresafe/riot-web#8f4f4065
