### ISSUE TITLE
confirm identity server invitations work with send-grid

### ISSUE THREAD

**Issue by dduran1967** [wiresafe/wiresafe-deploy#3]
Please verify that the integration server will send through send grid.

**Comment by maxidorius** [comment]
We'll need to investigate how to make this work. This can range from a simple configuration change to refactoring code to integrate custom API. Can't accurately estimate workload due to prior investigation, but could easily be some hours of dev.

**Comment by dduran1967** [comment]
I will test this with send-grid.

**Comment by maxidorius** [comment]
See https://support.google.com/a/answer/2956491 for a possible easy fix

**Comment by dduran1967** [comment]
or find an alternative solution.

**Comment by dduran1967** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [SMTP Relay / Send Grid](https://trello.com/c/UJPni1f3/34-smtp-relay-send-grid)

**Comment by maxidorius** [comment]
done using https://github.com/kamax-io/mxisd/commit/f3bbc7c7c6493a4d444e167867d2d042fce0d01d as base for matrix-identity image and the configuration snippet:
```
{
...
  "notification": {
    "handler": {
      "email": "sendgrid"
    },
    "handlers": {
      "sendgrid": {
        "api": {
          "key": "<api key>"
        },
        "identity": {
          "from": "WireSafe",
          "name": "noreply@wiresafe.com"
        },
        "templates": {
          "invite": {
            "subject": "You have been invited to WireSafe",
            "body": {
              "text": "/etc/mxisd/email-invite-template.txt",
              "html": "/etc/mxisd/email-invite-template.html"
            }
          }
        }
      }
    }
  }
...
}
```
