### ISSUE TITLE
failed to join room on new invitation

### ISSUE THREAD

**Issue by dduran1967** [wiresafe/wiresafe-deploy#4]
After following an invitation link - I see a messaging saying I'm trying to view a room and to click to join.  But when I try to join I get   Failed to join room - No known servers

**Comment by maxidorius** [comment]
Not enough info to know what's going on. Could you give me a step by step, reproducible scenario with the exact values you entered?

**Comment by dduran1967** [comment]
1. confirm the invitee is a new account (email address is not in firebase auth)

2. login to riot-web (stage or prod) as the invitor with an account attached to our home server.

3. create a new private room

4. in riot, click the "invite to this room" button in the lower right corner and enter the target invitee email address from step 1. (note the room id)

5. follow the link in the invitation email (in a new session) and use the firebase UI to create a new account by the invitee email address.

6. after creating the account you will see a screen saying you are trying to access a room, click here to join the conversation. (Note the room id does not match the room id from step4 - not sure if this is relevant)

7. Clicking here results in a popup error: failed to join room - no known servers.

**Comment by dduran1967** [comment]
this was fixed by removing the bot
