### ISSUE TITLE
accounts created with firebase should capture user's name, phone and email when available

### ISSUE THREAD

**Issue by dduran1967** [wiresafe/wiresafe-deploy#5]
After creating a new account with firebase authentication - the email address and/or phone numbers are not showing up.

**Comment by maxidorius** [comment]
Technically doable, but serves no functional purpose in the current requirements.  

That info is only available to the synapse, and only the e-mail info would be used if synapse is configured to send notifications about pending non-read messages every day or so.
Anything relating to invites or lookups is done at the Identity server level and do not use the profile info of the user.

If needed, can be done in ~4 hours, redeployment included.

**Comment by dduran1967** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [accounts created with firebase should capture user's name, phone and email when available](https://trello.com/c/yOUBKRP2/43-accounts-created-with-firebase-should-capture-users-name-phone-and-email-when-available)

**Comment by maxidorius** [comment]
Done with at https://github.com/wiresafe/wiresafe-deploy/commit/c9eba1b4a582d106e49bb4af90e9883a437212e5
